### ISSUE TITLE
missing the 'ugi.xlsx' when running the pipeline

### ISSUE THREAD

**Issue by lbgbox** [GradinaruLab/useqfish_probedesign#3]
UGI file is missing for the probe design pipeline 'useqfish_probedesign'.
Where can download this file?

**Comment by minjeejang** [comment]
Sorry for the inconvenience. ugi.xlsx file has been uploaded.

**Comment by lbgbox** [comment]
> Sorry for the inconvenience. ugi.xlsx file has been uploaded.

Hi Min Jee, 
Thanks for upload the ugi.xlsx file.
I still have problem about the HTTP error.
Do you know how to fix it?
Thanks!
Baoguo

 ###
File "/home/labs/amit/lbg/.conda/envs/test2/lib/python3.9/urllib/request.py", line 641, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by minjeejang** [comment]
Hi Baoguo, 

Please check the followings: (1) is your computer connected to internet? (2) do you use your own email? (3) is your accession number for nucleotide, not protein? 

I can look it up too if you can copy here or email me your XX_probe_example.py file. 

Also, if nothing works, you can also put the sequence directly into the "sequence" variable as a string form, which will bypass urllib.

Let me know if it works!

**Comment by lbgbox** [comment]
Hi Min Jee,
Thanks for your suggestion.
I paste the sequence of gad1 to "sequence".
Now the error is no "db" file.
I also email you more the example.py file.
Thanks for your help!
Best!
Baoguo

**Comment by minjeejang** [comment]
Hi Baoguo,

Sorry again for the inconvenience. Here is the link where you can download DB files: https://doi.org/10.22002/b791z-fzd10
I also update readme as well.

**Comment by lbgbox** [comment]
> Hi Baoguo,
> 
> Sorry again for the inconvenience. Here is the link where you can download DB files: https://doi.org/10.22002/b791z-fzd10 I also update readme as well.

**Comment by lbgbox** [comment]
Hi Min Jee,
It Works! 
Thanks for your help!
I will email you for some more questions.
Best,
Baoguo
